### ISSUE TITLE
Wrong amount sent

### ISSUE THREAD

**Issue by avive** [spacemeshos/CLIWallet#12] opened 2020-05-18 15:54 UTC
I'm sending a tx from the CLIWallet to a network running v0.1.11 nodes.
Regardless of the amount I sent, the tx amount on the mesh is 4294967295.
An example:

```
$ tx
> Transfer coins from local account to another account.
<APP> INFO 03b 18:44:22.627 ▶ request: http://localhost:9090/v1/nonce, body: { "address": "0xc4eabd379d646beb6e065934cf7e9de59f8d43e7"}
<APP> INFO 03c 18:44:22.629 ▶ response body: {"value":"13"}
<APP> INFO 03d 18:44:22.629 ▶ request: http://localhost:9090/v1/balance, body: { "address": "0xc4eabd379d646beb6e065934cf7e9de59f8d43e7"}
<APP> INFO 03e 18:44:22.630 ▶ response body: {"value":"99999978492993385"}
$ Enter or paste destination address: 0x3696af3ab5c082b1817de5b6d7190423dc68e302
$ Enter amount to transfer in Smidge (SMD): 999999999999999
$ Use default gas price (1 Smidge)? (y/n) n
$ Enter transaction gas price:99999
> Transaction summary:
> From:   0xC4EABd379D646beb6e065934CF7e9de59f8D43E7
> To:     0x3696af3aB5C082B1817DE5B6d7190423dc68E302
> Amount: 999999999999999
> Gas:    99999
> Nonce:  13
$ Confirm transaction (y/n): y
<APP> INFO 03f 18:44:36.397 ▶ request: http://localhost:9090/v1/submittransaction, body: { "tx": [0,0,0,0,0,0,0,13,54,150,175,58,181,192,130,177,129,125,229,182,215,25,4,35,220,104,227,2,0,0,0,0,0,0,0,100,0,0,0,0,0,1,134,159,0,0,0,0,255,255,255,255,203,193,64,84,5,226,23,183,150,15,161,2,27,15,88,201,100,198,76,171,27,115,234,169,170,88,19,122,172,243,188,226,42,66,155,98,151,12,146,185,17,197,251,113,146,159,214,84,239,150,254,123,105,18,73,122,166,168,186,232,228,141,4,9]}
<APP> INFO 040 18:44:36.400 ▶ response body: {"value":"ok","id":"1ed242d20306b9a0fdcef606dc462902de987cd2520a53156f877b4508917708"}
> tx submitted, id: 1ed242d20306b9a0fdcef606dc462902de987cd2520a53156f877b4508917708
```

TX info via the api returns this:

```
{
    "txId": {
        "id": "HtJC0gMGuaD9zvYG3EYpAt6YfNJSClMVb4d7RQiRdwg="
    },
    "sender": {
        "address": "c4eabd379d646beb6e065934cf7e9de59f8d43e7"
    },
    "receiver": {
        "address": "3696af3ab5c082b1817de5b6d7190423dc68e302"
    },
    "amount": "4294967295",
    "fee": "99999",
    "status": "PENDING"
}
```

@noamnelke @moshababo @IlyaVi

**Comment by lrettig** [comment] 2020-05-18 16:11
See also https://github.com/spacemeshos/go-spacemesh/issues/2006

**Comment by avive** [comment] 2020-05-18 16:17
Seems to be only for large amounts which are still much lower than that account balance.

**Comment by noamnelke** [comment] 2020-05-18 18:07
The actual amount sent is the maximum 32-byte integer (2^32 = 4,294,967,295).

This line is to blame:
https://github.com/spacemeshos/CLIWallet/blob/f8a37527def2bfe470649185abefbf413a3bc9c5/repl/repl.go#L260

It parses the string as a 32-bit integer, although it looks like all the variables this value gets placed in are `uint64`s. I guess changing this one value to 64 should fix it (but we should add a unit test for that, too).

**Comment by noamnelke** [comment] 2020-05-19 06:46
I've made the fix - please pull, rebuild and test it and let me know if it's fixed so we can close this issue.

@avive @lrettig

**Comment by lrettig** [comment] 2020-05-19 17:49
I can confirm that I was able to create and broadcast a tx with a larger tx size. Thanks.

**Comment by noamnelke** [comment] 2020-05-19 17:51
👍🏻

**Closed by noamnelke** 2020-05-19 17:51 UTC
